---
deployment:
  tasks:
    - export DEPLOYPATH=/home/karzinte/repositories/karzintell/
    - /bin/cp -R apps $DEPLOYPATH
    - /bin/cp package.json $DEPLOYPATH
    - /bin/cp package-lock.json $DEPLOYPATH
