-- ============================================================================
-- کارزینتل — Supabase/PostgreSQL schema
-- ============================================================================
-- این فایل را در SQL Editor پروژه Supabase اجرا کنید.
-- طراحی شده برای اجرای امن چندباره روی یک پروژه تازه؛ داده‌های موجود حذف نمی‌شوند.
-- API فعلی فروشگاه از کاربران داخلی public.users استفاده می‌کند و می‌تواند با
-- DATABASE_URL اتصال PostgreSQL/Supabase را دریافت کند. auth_user_id امکان مهاجرت
-- تدریجی به Supabase Auth را فراهم می‌کند. هیچ secret یا رمز عبوری در این فایل نیست.
-- واحد پول همه مبالغ: ریال.
-- ============================================================================

CREATE EXTENSION IF NOT EXISTS pgcrypto;

CREATE TABLE IF NOT EXISTS public.users (
  id                   BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  auth_user_id         UUID NULL,
  full_name            VARCHAR(120)  NOT NULL,
  email                VARCHAR(190)  NULL,
  phone                VARCHAR(15)   NOT NULL,
  password_hash        VARCHAR(255)  NULL,
  national_code        VARCHAR(10)   NULL,
  avatar_path          VARCHAR(500)  NULL,
  status               TEXT NOT NULL DEFAULT 'pending',
  must_change_password BOOLEAN    NOT NULL DEFAULT FALSE,
  two_factor_enabled   BOOLEAN    NOT NULL DEFAULT FALSE,
  two_factor_secret    VARCHAR(64)   NULL,
  email_verified_at    TIMESTAMPTZ      NULL,
  phone_verified_at    TIMESTAMPTZ      NULL,
  last_login_at        TIMESTAMPTZ      NULL,
  created_at           TIMESTAMPTZ      NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at           TIMESTAMPTZ      NOT NULL DEFAULT CURRENT_TIMESTAMP,
  deleted_at           TIMESTAMPTZ      NULL,
  PRIMARY KEY (id),
  CONSTRAINT uq_users_auth_user UNIQUE (auth_user_id),
  CONSTRAINT uq_users_email UNIQUE (email),
  CONSTRAINT uq_users_phone UNIQUE (phone)
);

CREATE TABLE IF NOT EXISTS public.roles (
  id          INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  name        VARCHAR(50)  NOT NULL,
  label       VARCHAR(100) NOT NULL,
  description VARCHAR(255) NULL,
  is_system   BOOLEAN   NOT NULL DEFAULT FALSE,
  created_at  TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at  TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  CONSTRAINT uq_roles_name UNIQUE (name)
);

CREATE TABLE IF NOT EXISTS public.permissions (
  id         INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  name       VARCHAR(100) NOT NULL,
  label      VARCHAR(150) NOT NULL,
  group_name VARCHAR(50)  NOT NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  CONSTRAINT uq_permissions_name UNIQUE (name)
);

CREATE TABLE IF NOT EXISTS public.role_user (
  role_id     INTEGER    NOT NULL,
  user_id     BIGINT NOT NULL,
  assigned_by BIGINT NULL,
  created_at  TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (role_id, user_id),
  CONSTRAINT fk_ru_role FOREIGN KEY (role_id) REFERENCES roles (id) ON DELETE CASCADE,
  CONSTRAINT fk_ru_user FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE,
  CONSTRAINT fk_ru_assigned_by FOREIGN KEY (assigned_by) REFERENCES users (id) ON DELETE SET NULL
);

CREATE TABLE IF NOT EXISTS public.permission_role (
  permission_id INTEGER NOT NULL,
  role_id       INTEGER NOT NULL,
  PRIMARY KEY (permission_id, role_id),
  CONSTRAINT fk_pr_permission FOREIGN KEY (permission_id) REFERENCES permissions (id) ON DELETE CASCADE,
  CONSTRAINT fk_pr_role FOREIGN KEY (role_id) REFERENCES roles (id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS public.permission_user (
  permission_id INTEGER    NOT NULL,
  user_id       BIGINT NOT NULL,
  type          TEXT NOT NULL DEFAULT 'allow',
  granted_by    BIGINT NULL,
  created_at    TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (permission_id, user_id),
  CONSTRAINT fk_pu_permission FOREIGN KEY (permission_id) REFERENCES permissions (id) ON DELETE CASCADE,
  CONSTRAINT fk_pu_user FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE,
  CONSTRAINT fk_pu_granted_by FOREIGN KEY (granted_by) REFERENCES users (id) ON DELETE SET NULL
);

CREATE TABLE IF NOT EXISTS public.user_addresses (
  id             BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  user_id        BIGINT NOT NULL,
  title          VARCHAR(50)  NOT NULL DEFAULT 'آدرس من',
  receiver_name  VARCHAR(120) NOT NULL,
  receiver_phone VARCHAR(15)  NOT NULL,
  province       VARCHAR(50)  NOT NULL,
  city           VARCHAR(50)  NOT NULL,
  postal_code    VARCHAR(10)  NULL,
  address        TEXT         NOT NULL,
  plaque         VARCHAR(20)  NULL,
  unit           VARCHAR(20)  NULL,
  latitude       DECIMAL(10,7) NULL,
  longitude      DECIMAL(10,7) NULL,
  is_default     BOOLEAN NOT NULL DEFAULT FALSE,
  created_at     TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at     TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  deleted_at     TIMESTAMPTZ NULL,
  PRIMARY KEY (id),
  CONSTRAINT fk_addr_user FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS public.verification_codes (
  id          BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  channel     TEXT NOT NULL,
  target      VARCHAR(190) NOT NULL,
  code_hash   VARCHAR(255) NOT NULL,
  purpose     TEXT NOT NULL DEFAULT 'login',
  attempts    SMALLINT NOT NULL DEFAULT 0,
  expires_at  TIMESTAMPTZ NOT NULL,
  consumed_at TIMESTAMPTZ NULL,
  created_at  TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.refresh_tokens (
  id          BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  user_id     BIGINT NOT NULL,
  token_hash  CHAR(64) NOT NULL,
  user_agent  VARCHAR(255) NULL,
  ip          VARCHAR(45) NULL,
  expires_at  TIMESTAMPTZ NOT NULL,
  revoked_at  TIMESTAMPTZ NULL,
  created_at  TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  CONSTRAINT uq_rt_token UNIQUE (token_hash),
  CONSTRAINT fk_rt_user FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE
);

-- ============================================================================
-- 2) کاتالوگ محصولات (Catalog)
-- ============================================================================

CREATE TABLE IF NOT EXISTS public.brands (
  id          INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  name        VARCHAR(100) NOT NULL,
  slug        VARCHAR(140) NOT NULL,
  logo_path   VARCHAR(500) NULL,
  description TEXT NULL,
  website     VARCHAR(255) NULL,
  is_active   BOOLEAN NOT NULL DEFAULT TRUE,
  sort_order  INTEGER NOT NULL DEFAULT 0,
  created_at  TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at  TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  deleted_at  TIMESTAMPTZ NULL,
  PRIMARY KEY (id),
  CONSTRAINT uq_brands_slug UNIQUE (slug)
);

CREATE TABLE IF NOT EXISTS public.categories (
  id               INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  parent_id        INTEGER NULL,
  name             VARCHAR(120) NOT NULL,
  slug             VARCHAR(160) NOT NULL,
  description      TEXT NULL,
  image_path       VARCHAR(500) NULL,
  icon             VARCHAR(80)  NULL,
  sort_order       INTEGER NOT NULL DEFAULT 0,
  is_active        BOOLEAN NOT NULL DEFAULT TRUE,
  meta_title       VARCHAR(190) NULL,
  meta_description VARCHAR(300) NULL,
  created_at       TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at       TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  deleted_at       TIMESTAMPTZ NULL,
  PRIMARY KEY (id),
  CONSTRAINT uq_categories_slug UNIQUE (slug),
  CONSTRAINT fk_cat_parent FOREIGN KEY (parent_id) REFERENCES categories (id) ON DELETE RESTRICT
);

CREATE TABLE IF NOT EXISTS public.attributes (
  id            INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  name          VARCHAR(100) NOT NULL,
  code          VARCHAR(100) NOT NULL,
  type          TEXT NOT NULL DEFAULT 'select',
  unit          VARCHAR(20) NULL,
  group_name    VARCHAR(100) NULL,
  is_filterable BOOLEAN NOT NULL DEFAULT TRUE,
  created_at    TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at    TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  CONSTRAINT uq_attrs_code UNIQUE (code)
);

CREATE TABLE IF NOT EXISTS public.attribute_values (
  id           INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  attribute_id INTEGER NOT NULL,
  value        VARCHAR(190) NOT NULL,
  meta         JSONB NULL,
  sort_order   INTEGER NOT NULL DEFAULT 0,
  PRIMARY KEY (id),
  CONSTRAINT uq_attrval UNIQUE (attribute_id, value),
  CONSTRAINT fk_attrval_attr FOREIGN KEY (attribute_id) REFERENCES attributes (id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS public.category_attribute (
  category_id  INTEGER NOT NULL,
  attribute_id INTEGER NOT NULL,
  is_variant   BOOLEAN NOT NULL DEFAULT FALSE,
  is_required  BOOLEAN NOT NULL DEFAULT FALSE,
  sort_order   INTEGER NOT NULL DEFAULT 0,
  PRIMARY KEY (category_id, attribute_id),
  CONSTRAINT fk_ca_cat FOREIGN KEY (category_id) REFERENCES categories (id) ON DELETE CASCADE,
  CONSTRAINT fk_ca_attr FOREIGN KEY (attribute_id) REFERENCES attributes (id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS public.products (
  id                BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  code              VARCHAR(50)  NULL,
  category_id       INTEGER NOT NULL,
  brand_id          INTEGER NULL,
  name              VARCHAR(190) NOT NULL,
  slug              VARCHAR(220) NOT NULL,
  short_description VARCHAR(500) NULL,
  description       TEXT NULL,
  features          JSONB NULL,
  status            TEXT NOT NULL DEFAULT 'draft',
  published_at      TIMESTAMPTZ NULL,
  weight_g          INTEGER NULL,
  length_cm         DECIMAL(6,2) NULL,
  width_cm          DECIMAL(6,2) NULL,
  height_cm         DECIMAL(6,2) NULL,
  warranty_months   INTEGER NULL,
  rating_avg        DECIMAL(3,2) NOT NULL DEFAULT 0,
  rating_count      INTEGER NOT NULL DEFAULT 0,
  view_count        BIGINT NOT NULL DEFAULT 0,
  sold_count        BIGINT NOT NULL DEFAULT 0,
  min_price         BIGINT NULL,
  max_price         BIGINT NULL,
  meta_title        VARCHAR(190) NULL,
  meta_description  VARCHAR(300) NULL,
  created_at        TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at        TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  deleted_at        TIMESTAMPTZ NULL,
  PRIMARY KEY (id),
  CONSTRAINT uq_products_slug UNIQUE (slug),
  CONSTRAINT uq_products_code UNIQUE (code),
  CONSTRAINT fk_products_cat FOREIGN KEY (category_id) REFERENCES categories (id) ON DELETE RESTRICT,
  CONSTRAINT fk_products_brand FOREIGN KEY (brand_id) REFERENCES brands (id) ON DELETE SET NULL
);

CREATE TABLE IF NOT EXISTS public.product_variants (
  id               BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  product_id       BIGINT NOT NULL,
  sku              VARCHAR(64)  NOT NULL,
  barcode          VARCHAR(32)  NULL,
  title            VARCHAR(190) NULL,
  price            BIGINT NOT NULL,
  compare_at_price BIGINT NULL,
  cost_price       BIGINT NULL,
  stock_total      INTEGER NOT NULL DEFAULT 0,
  weight_g         INTEGER NULL,
  is_default       BOOLEAN NOT NULL DEFAULT FALSE,
  is_active        BOOLEAN NOT NULL DEFAULT TRUE,
  created_at       TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at       TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  deleted_at       TIMESTAMPTZ NULL,
  PRIMARY KEY (id),
  CONSTRAINT uq_variants_sku UNIQUE (sku),
  CONSTRAINT fk_variants_product FOREIGN KEY (product_id) REFERENCES products (id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS public.product_variant_values (
  variant_id         BIGINT NOT NULL,
  attribute_id       INTEGER NOT NULL,
  attribute_value_id INTEGER NOT NULL,
  PRIMARY KEY (variant_id, attribute_id),
  CONSTRAINT fk_pvv_variant FOREIGN KEY (variant_id) REFERENCES product_variants (id) ON DELETE CASCADE,
  CONSTRAINT fk_pvv_attr FOREIGN KEY (attribute_id) REFERENCES attributes (id) ON DELETE CASCADE,
  CONSTRAINT fk_pvv_value FOREIGN KEY (attribute_value_id) REFERENCES attribute_values (id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS public.product_images (
  id         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  product_id BIGINT NOT NULL,
  variant_id BIGINT NULL,
  path       VARCHAR(500) NOT NULL,
  alt        VARCHAR(190) NULL,
  sort_order INTEGER NOT NULL DEFAULT 0,
  is_primary BOOLEAN NOT NULL DEFAULT FALSE,
  created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  CONSTRAINT fk_pimg_product FOREIGN KEY (product_id) REFERENCES products (id) ON DELETE CASCADE,
  CONSTRAINT fk_pimg_variant FOREIGN KEY (variant_id) REFERENCES product_variants (id) ON DELETE SET NULL
);

CREATE TABLE IF NOT EXISTS public.product_videos (
  id          BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  product_id  BIGINT NOT NULL,
  title       VARCHAR(190) NULL,
  provider    TEXT NOT NULL DEFAULT 'upload',
  source_url  VARCHAR(500) NOT NULL,
  poster_path VARCHAR(500) NULL,
  sort_order  INTEGER NOT NULL DEFAULT 0,
  created_at  TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  CONSTRAINT fk_pvid_product FOREIGN KEY (product_id) REFERENCES products (id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS public.tags (
  id         INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  name       VARCHAR(80)  NOT NULL,
  slug       VARCHAR(120) NOT NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  CONSTRAINT uq_tags_name UNIQUE (name),
  CONSTRAINT uq_tags_slug UNIQUE (slug)
);

CREATE TABLE IF NOT EXISTS public.product_tags (
  product_id BIGINT NOT NULL,
  tag_id     INTEGER NOT NULL,
  PRIMARY KEY (product_id, tag_id),
  CONSTRAINT fk_pt_product FOREIGN KEY (product_id) REFERENCES products (id) ON DELETE CASCADE,
  CONSTRAINT fk_pt_tag FOREIGN KEY (tag_id) REFERENCES tags (id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS public.product_relations (
  product_id         BIGINT NOT NULL,
  related_product_id BIGINT NOT NULL,
  type               TEXT NOT NULL DEFAULT 'related',
  sort_order         INTEGER NOT NULL DEFAULT 0,
  PRIMARY KEY (product_id, related_product_id, type),
  CONSTRAINT chk_prel_not_self CHECK (product_id <> related_product_id),
  CONSTRAINT fk_prel_product FOREIGN KEY (product_id) REFERENCES products (id) ON DELETE CASCADE,
  CONSTRAINT fk_prel_related FOREIGN KEY (related_product_id) REFERENCES products (id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS public.product_attributes (
  id                 BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  product_id         BIGINT NOT NULL,
  attribute_id       INTEGER NOT NULL,
  attribute_value_id INTEGER NULL,
  custom_value       VARCHAR(500) NULL,
  sort_order         INTEGER NOT NULL DEFAULT 0,
  PRIMARY KEY (id),
  CONSTRAINT fk_pattr_product FOREIGN KEY (product_id) REFERENCES products (id) ON DELETE CASCADE,
  CONSTRAINT fk_pattr_attr FOREIGN KEY (attribute_id) REFERENCES attributes (id) ON DELETE CASCADE,
  CONSTRAINT fk_pattr_value FOREIGN KEY (attribute_value_id) REFERENCES attribute_values (id) ON DELETE SET NULL
);

-- ============================================================================
-- 3) انبار و موجودی (Inventory)
-- ============================================================================

CREATE TABLE IF NOT EXISTS public.warehouses (
  id          INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  name        VARCHAR(100) NOT NULL,
  code        VARCHAR(30)  NOT NULL,
  province    VARCHAR(50)  NULL,
  city        VARCHAR(50)  NULL,
  address     TEXT         NULL,
  postal_code VARCHAR(10)  NULL,
  phone       VARCHAR(15)  NULL,
  is_active   BOOLEAN NOT NULL DEFAULT TRUE,
  created_at  TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at  TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  CONSTRAINT uq_warehouses_code UNIQUE (code)
);

CREATE TABLE IF NOT EXISTS public.inventory (
  variant_id           BIGINT NOT NULL,
  warehouse_id         INTEGER NOT NULL,
  quantity             INTEGER NOT NULL DEFAULT 0,
  reserved             INTEGER NOT NULL DEFAULT 0,
  low_stock_threshold  INTEGER NOT NULL DEFAULT 5,
  updated_at           TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (variant_id, warehouse_id),
  CONSTRAINT fk_inv_variant FOREIGN KEY (variant_id) REFERENCES product_variants (id) ON DELETE CASCADE,
  CONSTRAINT fk_inv_warehouse FOREIGN KEY (warehouse_id) REFERENCES warehouses (id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS public.stock_movements (
  id             BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  variant_id     BIGINT NOT NULL,
  warehouse_id   INTEGER NOT NULL,
  type           TEXT NOT NULL,
  quantity       INTEGER NOT NULL,
  qty_before     INTEGER NOT NULL,
  qty_after      INTEGER NOT NULL,
  reference_type VARCHAR(30) NULL,
  reference_id   BIGINT NULL,
  note           VARCHAR(500) NULL,
  created_by     BIGINT NULL,
  created_at     TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  CONSTRAINT fk_sm_variant FOREIGN KEY (variant_id) REFERENCES product_variants (id) ON DELETE CASCADE,
  CONSTRAINT fk_sm_warehouse FOREIGN KEY (warehouse_id) REFERENCES warehouses (id) ON DELETE CASCADE,
  CONSTRAINT fk_sm_user FOREIGN KEY (created_by) REFERENCES users (id) ON DELETE SET NULL
);

-- ============================================================================
-- 4) سبد خرید و کوپن (Cart & Coupons)
-- ============================================================================

CREATE TABLE IF NOT EXISTS public.coupons (
  id               INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  code             VARCHAR(50) NOT NULL,
  title            VARCHAR(120) NULL,
  type             TEXT NOT NULL,
  value            DECIMAL(10,2) NOT NULL,
  max_discount     BIGINT NULL,
  min_cart_amount  BIGINT NOT NULL DEFAULT 0,
  usage_limit      INTEGER NULL,
  per_user_limit   INTEGER NOT NULL DEFAULT 1,
  used_count       INTEGER NOT NULL DEFAULT 0,
  campaign         VARCHAR(120) NULL,
  product_ids      JSONB NULL,
  category_ids     JSONB NULL,
  starts_at        TIMESTAMPTZ NULL,
  expires_at       TIMESTAMPTZ NULL,
  is_active        BOOLEAN NOT NULL DEFAULT TRUE,
  created_at       TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at       TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  deleted_at       TIMESTAMPTZ NULL,
  PRIMARY KEY (id),
  CONSTRAINT uq_coupons_code UNIQUE (code)
);

CREATE TABLE IF NOT EXISTS public.carts (
  id         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  user_id    BIGINT NULL,
  session_id VARCHAR(36) NULL,
  status     TEXT NOT NULL DEFAULT 'open',
  coupon_id  INTEGER NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  CONSTRAINT fk_carts_user FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE,
  CONSTRAINT fk_carts_coupon FOREIGN KEY (coupon_id) REFERENCES coupons (id) ON DELETE SET NULL
);

CREATE TABLE IF NOT EXISTS public.cart_items (
  id         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  cart_id    BIGINT NOT NULL,
  variant_id BIGINT NOT NULL,
  quantity   INTEGER NOT NULL DEFAULT 1,
  unit_price BIGINT NOT NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  CONSTRAINT uq_cart_item UNIQUE (cart_id, variant_id),
  CONSTRAINT fk_ci_cart FOREIGN KEY (cart_id) REFERENCES carts (id) ON DELETE CASCADE,
  CONSTRAINT fk_ci_variant FOREIGN KEY (variant_id) REFERENCES product_variants (id) ON DELETE CASCADE
);

-- ============================================================================
-- 5) سفارش و پرداخت (Orders & Payments)
-- ============================================================================

CREATE TABLE IF NOT EXISTS public.orders (
  id               BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  code             VARCHAR(20) NOT NULL,
  user_id          BIGINT NOT NULL,
  status           TEXT NOT NULL DEFAULT 'pending_payment',
  payment_status   TEXT NOT NULL DEFAULT 'unpaid',
  subtotal         BIGINT NOT NULL DEFAULT 0,
  discount_total   BIGINT NOT NULL DEFAULT 0,
  shipping_cost    BIGINT NOT NULL DEFAULT 0,
  tax_total        BIGINT NOT NULL DEFAULT 0,
  grand_total      BIGINT NOT NULL DEFAULT 0,
  coupon_id        INTEGER NULL,
  coupon_code      VARCHAR(50) NULL,
  shipping_method  VARCHAR(100) NULL,
  address_json     JSONB NOT NULL,
  customer_note    TEXT NULL,
  admin_note       TEXT NULL,
  ip               VARCHAR(45) NULL,
  user_agent       VARCHAR(255) NULL,
  placed_at        TIMESTAMPTZ NULL,
  paid_at          TIMESTAMPTZ NULL,
  delivered_at     TIMESTAMPTZ NULL,
  cancelled_at     TIMESTAMPTZ NULL,
  cancel_reason    VARCHAR(300) NULL,
  created_at       TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at       TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  deleted_at       TIMESTAMPTZ NULL,
  PRIMARY KEY (id),
  CONSTRAINT uq_orders_code UNIQUE (code),
  CONSTRAINT fk_orders_user FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE RESTRICT,
  CONSTRAINT fk_orders_coupon FOREIGN KEY (coupon_id) REFERENCES coupons (id) ON DELETE SET NULL
);

CREATE TABLE IF NOT EXISTS public.order_items (
  id              BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  order_id        BIGINT NOT NULL,
  product_id      BIGINT NOT NULL,
  variant_id      BIGINT NOT NULL,
  sku             VARCHAR(64)  NOT NULL,
  product_name    VARCHAR(190) NOT NULL,
  variant_title   VARCHAR(190) NULL,
  unit_price      BIGINT NOT NULL,
  quantity        INTEGER NOT NULL,
  discount_amount BIGINT NOT NULL DEFAULT 0,
  total_price     BIGINT NOT NULL,
  warranty_months INTEGER NULL,
  created_at      TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  CONSTRAINT fk_oi_order FOREIGN KEY (order_id) REFERENCES orders (id) ON DELETE CASCADE,
  CONSTRAINT fk_oi_product FOREIGN KEY (product_id) REFERENCES products (id) ON DELETE RESTRICT,
  CONSTRAINT fk_oi_variant FOREIGN KEY (variant_id) REFERENCES product_variants (id) ON DELETE RESTRICT
);

CREATE TABLE IF NOT EXISTS public.order_status_histories (
  id         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  order_id   BIGINT NOT NULL,
  from_status VARCHAR(30) NULL,
  to_status   VARCHAR(30) NOT NULL,
  note        VARCHAR(500) NULL,
  changed_by  BIGINT NULL,
  created_at  TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  CONSTRAINT fk_osh_order FOREIGN KEY (order_id) REFERENCES orders (id) ON DELETE CASCADE,
  CONSTRAINT fk_osh_user FOREIGN KEY (changed_by) REFERENCES users (id) ON DELETE SET NULL
);

CREATE TABLE IF NOT EXISTS public.payments (
  id          BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  order_id    BIGINT NULL,
  purpose     TEXT NOT NULL DEFAULT 'order',
  gateway     TEXT NOT NULL,
  amount      BIGINT NOT NULL,
  currency    VARCHAR(3) NOT NULL DEFAULT 'IRR',
  status      TEXT NOT NULL DEFAULT 'initiated',
  authority   VARCHAR(100) NULL,
  ref_id      VARCHAR(100) NULL,
  card_pan    VARCHAR(20)  NULL,
  fee         BIGINT NULL,
  payload     JSONB NULL,
  paid_at     TIMESTAMPTZ NULL,
  created_at  TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at  TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  CONSTRAINT uq_pay_authority UNIQUE (gateway, authority),
  CONSTRAINT fk_pay_order FOREIGN KEY (order_id) REFERENCES orders (id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS public.shipments (
  id            BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  order_id      BIGINT NOT NULL,
  provider      VARCHAR(50) NOT NULL DEFAULT 'post',
  method        VARCHAR(100) NULL,
  tracking_code VARCHAR(50) NULL,
  status        TEXT NOT NULL DEFAULT 'pending',
  cost          BIGINT NULL,
  shipped_at    TIMESTAMPTZ NULL,
  delivered_at  TIMESTAMPTZ NULL,
  created_at    TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at    TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  CONSTRAINT fk_ship_order FOREIGN KEY (order_id) REFERENCES orders (id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS public.coupon_usages (
  id              BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  coupon_id       INTEGER NOT NULL,
  user_id         BIGINT NOT NULL,
  order_id        BIGINT NOT NULL,
  discount_amount BIGINT NOT NULL,
  created_at      TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  CONSTRAINT uq_cu_order UNIQUE (coupon_id, order_id),
  CONSTRAINT fk_cu_coupon FOREIGN KEY (coupon_id) REFERENCES coupons (id) ON DELETE CASCADE,
  CONSTRAINT fk_cu_user FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE,
  CONSTRAINT fk_cu_order FOREIGN KEY (order_id) REFERENCES orders (id) ON DELETE CASCADE
);

-- 5-الف) کیف پول (Wallet — اختیاری)
CREATE TABLE IF NOT EXISTS public.wallets (
  id         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  user_id    BIGINT NOT NULL,
  balance    BIGINT NOT NULL DEFAULT 0,
  created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  CONSTRAINT uq_wallets_user UNIQUE (user_id),
  CONSTRAINT fk_wallets_user FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS public.wallet_transactions (
  id             BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  wallet_id      BIGINT NOT NULL,
  type           TEXT NOT NULL,
  amount         BIGINT NOT NULL,
  balance_after  BIGINT NOT NULL,
  reference_type VARCHAR(30) NULL,
  reference_id   BIGINT NULL,
  description    VARCHAR(300) NULL,
  created_at     TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  CONSTRAINT fk_wt_wallet FOREIGN KEY (wallet_id) REFERENCES wallets (id) ON DELETE CASCADE
);

-- ============================================================================
-- 6) بازخورد و تعامل (Reviews / Q&A / Wishlist)
-- ============================================================================

CREATE TABLE IF NOT EXISTS public.reviews (
  id            BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  product_id    BIGINT NOT NULL,
  user_id       BIGINT NOT NULL,
  order_item_id BIGINT NULL,
  rating        SMALLINT  NOT NULL CHECK (rating BETWEEN 1 AND 5),
  title         VARCHAR(150) NULL,
  body          TEXT NULL,
  pros          JSONB NULL,
  cons          JSONB NULL,
  status        TEXT NOT NULL DEFAULT 'pending',
  seller_reply  TEXT NULL,
  replied_at    TIMESTAMPTZ NULL,
  created_at    TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at    TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  deleted_at    TIMESTAMPTZ NULL,
  PRIMARY KEY (id),
  CONSTRAINT uq_review_user_product UNIQUE (product_id, user_id),
  CONSTRAINT fk_rev_product FOREIGN KEY (product_id) REFERENCES products (id) ON DELETE CASCADE,
  CONSTRAINT fk_rev_user FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE,
  CONSTRAINT fk_rev_order_item FOREIGN KEY (order_item_id) REFERENCES order_items (id) ON DELETE SET NULL
);

CREATE TABLE IF NOT EXISTS public.product_questions (
  id          BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  product_id  BIGINT NOT NULL,
  user_id     BIGINT NOT NULL,
  question    TEXT NOT NULL,
  answer      TEXT NULL,
  answered_by BIGINT NULL,
  status      TEXT NOT NULL DEFAULT 'pending',
  answered_at TIMESTAMPTZ NULL,
  created_at  TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  CONSTRAINT fk_pq_product FOREIGN KEY (product_id) REFERENCES products (id) ON DELETE CASCADE,
  CONSTRAINT fk_pq_user FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE,
  CONSTRAINT fk_pq_answerer FOREIGN KEY (answered_by) REFERENCES users (id) ON DELETE SET NULL
);

CREATE TABLE IF NOT EXISTS public.wishlists (
  user_id    BIGINT NOT NULL,
  product_id BIGINT NOT NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (user_id, product_id),
  CONSTRAINT fk_wl_user FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE,
  CONSTRAINT fk_wl_product FOREIGN KEY (product_id) REFERENCES products (id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS public.product_compares (
  user_id    BIGINT NOT NULL,
  product_id BIGINT NOT NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (user_id, product_id),
  CONSTRAINT fk_cmp_user FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE,
  CONSTRAINT fk_cmp_product FOREIGN KEY (product_id) REFERENCES products (id) ON DELETE CASCADE
);

-- ============================================================================
-- 6-الف) حمل‌ونقل (Shipping)
-- ============================================================================

CREATE TABLE IF NOT EXISTS public.shipping_zones (
  id         INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  name       VARCHAR(120) NOT NULL,
  provinces  JSONB NULL,
  cities     JSONB NULL,
  is_active  BOOLEAN NOT NULL DEFAULT TRUE,
  sort_order INTEGER NOT NULL DEFAULT 0,
  created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.shipping_methods (
  id          INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  zone_id     INTEGER NOT NULL,
  name        VARCHAR(120) NOT NULL,
  type        TEXT NOT NULL DEFAULT 'post',
  cost        BIGINT NOT NULL DEFAULT 0,
  free_above  BIGINT NULL,
  eta         VARCHAR(100) NULL,
  is_active   BOOLEAN NOT NULL DEFAULT TRUE,
  sort_order  INTEGER NOT NULL DEFAULT 0,
  created_at  TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at  TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  CONSTRAINT fk_sm_zone FOREIGN KEY (zone_id) REFERENCES shipping_zones (id) ON DELETE CASCADE
);

-- ============================================================================
-- 7) بازاریابی و مدیریت محتوا (CMS)
-- ============================================================================

CREATE TABLE IF NOT EXISTS public.banners (
  id                BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  title             VARCHAR(150) NOT NULL,
  subtitle          VARCHAR(300) NULL,
  image_path        VARCHAR(500) NOT NULL,
  mobile_image_path VARCHAR(500) NULL,
  link_url          VARCHAR(500) NULL,
  position          TEXT NOT NULL DEFAULT 'home_hero',
  sort_order        INTEGER NOT NULL DEFAULT 0,
  is_active         BOOLEAN NOT NULL DEFAULT TRUE,
  starts_at         TIMESTAMPTZ NULL,
  ends_at           TIMESTAMPTZ NULL,
  created_at        TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at        TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.pages (
  id               BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  title            VARCHAR(190) NOT NULL,
  slug             VARCHAR(220) NOT NULL,
  body             TEXT NOT NULL,
  status           TEXT NOT NULL DEFAULT 'draft',
  meta_title       VARCHAR(190) NULL,
  meta_description VARCHAR(300) NULL,
  created_at       TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at       TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  deleted_at       TIMESTAMPTZ NULL,
  PRIMARY KEY (id),
  CONSTRAINT uq_pages_slug UNIQUE (slug)
);

-- ============================================================================
-- 7-ب) وبلاگ و اخبار + سوالات متداول
-- ============================================================================

CREATE TABLE IF NOT EXISTS public.blog_posts (
  id               BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  title            VARCHAR(190) NOT NULL,
  slug             VARCHAR(220) NOT NULL,
  excerpt          VARCHAR(500) NULL,
  body             TEXT NOT NULL,
  cover_path       VARCHAR(500) NULL,
  kind             TEXT NOT NULL DEFAULT 'post',
  status           TEXT NOT NULL DEFAULT 'draft',
  author_id        BIGINT NULL,
  meta_title       VARCHAR(190) NULL,
  meta_description VARCHAR(300) NULL,
  published_at     TIMESTAMPTZ NULL,
  created_at       TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at       TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  deleted_at       TIMESTAMPTZ NULL,
  PRIMARY KEY (id),
  CONSTRAINT uq_blog_slug UNIQUE (slug),
  CONSTRAINT fk_blog_author FOREIGN KEY (author_id) REFERENCES users (id) ON DELETE SET NULL
);

CREATE TABLE IF NOT EXISTS public.faqs (
  id         INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  question   VARCHAR(300) NOT NULL,
  answer     TEXT NOT NULL,
  sort_order INTEGER NOT NULL DEFAULT 0,
  is_active  BOOLEAN NOT NULL DEFAULT TRUE,
  created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.tickets (
  id               BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  user_id    BIGINT NOT NULL,
  order_id   BIGINT NULL,
  subject    VARCHAR(190) NOT NULL,
  department TEXT NOT NULL DEFAULT 'support',
  priority   TEXT NOT NULL DEFAULT 'medium',
  status     TEXT NOT NULL DEFAULT 'open',
  closed_at  TIMESTAMPTZ NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  CONSTRAINT fk_tk_user FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE,
  CONSTRAINT fk_tk_order FOREIGN KEY (order_id) REFERENCES orders (id) ON DELETE SET NULL
);

CREATE TABLE IF NOT EXISTS public.ticket_messages (
  id          BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  ticket_id   BIGINT NOT NULL,
  sender_id   BIGINT NOT NULL,
  body        TEXT NOT NULL,
  attachments JSONB NULL,
  is_internal BOOLEAN NOT NULL DEFAULT FALSE,
  created_at  TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  CONSTRAINT fk_tm_ticket FOREIGN KEY (ticket_id) REFERENCES tickets (id) ON DELETE CASCADE,
  CONSTRAINT fk_tm_sender FOREIGN KEY (sender_id) REFERENCES users (id) ON DELETE CASCADE
);

-- ============================================================================
-- 8) زیرساخت: فایل‌ها، اعلان‌ها، تنظیمات، لاگ
-- ============================================================================

CREATE TABLE IF NOT EXISTS public.files (
  id            BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  disk          VARCHAR(20) NOT NULL DEFAULT 's3',
  path          VARCHAR(500) NOT NULL,
  original_name VARCHAR(255) NULL,
  mime_type     VARCHAR(100) NULL,
  size_bytes    BIGINT NULL,
  purpose       VARCHAR(50) NULL,
  owner_id      BIGINT NULL,
  created_at    TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  CONSTRAINT uq_files_path UNIQUE (disk, path),
  CONSTRAINT fk_files_owner FOREIGN KEY (owner_id) REFERENCES users (id) ON DELETE SET NULL
);

CREATE TABLE IF NOT EXISTS public.notifications (
  id         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  user_id    BIGINT NOT NULL,
  type       VARCHAR(50) NOT NULL,
  title      VARCHAR(190) NOT NULL,
  body       VARCHAR(500) NULL,
  data       JSONB NULL,
  channel    TEXT NOT NULL DEFAULT 'database',
  read_at    TIMESTAMPTZ NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  CONSTRAINT fk_notif_user FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS public.push_subscriptions (
  id         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  user_id    BIGINT NOT NULL,
  endpoint   VARCHAR(500) NOT NULL,
  p256dh     VARCHAR(255) NOT NULL,
  auth       VARCHAR(255) NOT NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  CONSTRAINT uq_push_endpoint UNIQUE (endpoint),
  CONSTRAINT fk_push_user FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS public.settings (
  "key"       VARCHAR(100) NOT NULL,
  "value"     TEXT NULL,
  "group"     VARCHAR(50) NOT NULL DEFAULT 'general',
  type        TEXT NOT NULL DEFAULT 'string',
  is_public   BOOLEAN NOT NULL DEFAULT FALSE,
  updated_by  BIGINT NULL,
  updated_at  TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY ("key"),
  CONSTRAINT fk_settings_user FOREIGN KEY (updated_by) REFERENCES users (id) ON DELETE SET NULL
);

CREATE TABLE IF NOT EXISTS public.audit_logs (
  id           BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  user_id      BIGINT NULL,
  action       VARCHAR(100) NOT NULL,
  subject_type VARCHAR(50) NULL,
  subject_id   BIGINT NULL,
  old_values   JSONB NULL,
  new_values   JSONB NULL,
  ip           VARCHAR(45) NULL,
  user_agent   VARCHAR(255) NULL,
  created_at   TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  CONSTRAINT fk_audit_user FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE SET NULL
);


-- ============================================================================
-- Operational extensions: stock alerts, support chat, atomic stock RPCs, RLS
-- ============================================================================

CREATE TABLE IF NOT EXISTS public.stock_alerts (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  variant_id BIGINT NOT NULL REFERENCES public.product_variants(id) ON DELETE CASCADE,
  warehouse_id INTEGER NOT NULL REFERENCES public.warehouses(id) ON DELETE CASCADE,
  available INTEGER NOT NULL DEFAULT 0 CHECK (available >= 0),
  threshold INTEGER NOT NULL DEFAULT 5 CHECK (threshold >= 0),
  alert_type TEXT NOT NULL CHECK (alert_type IN ('low_stock', 'out_of_stock')),
  status TEXT NOT NULL DEFAULT 'open' CHECK (status IN ('open', 'resolved')),
  last_notified_at TIMESTAMPTZ NULL,
  resolved_at TIMESTAMPTZ NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  CONSTRAINT uq_stock_alert_state UNIQUE (variant_id, warehouse_id, alert_type, status)
);

CREATE TABLE IF NOT EXISTS public.chat_threads (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id BIGINT NOT NULL REFERENCES public.users(id) ON DELETE CASCADE,
  assigned_to BIGINT NULL REFERENCES public.users(id) ON DELETE SET NULL,
  subject VARCHAR(190) NULL,
  status TEXT NOT NULL DEFAULT 'open' CHECK (status IN ('open', 'pending_customer', 'pending_operator', 'closed')),
  last_message_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS public.chat_messages (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  thread_id BIGINT NOT NULL REFERENCES public.chat_threads(id) ON DELETE CASCADE,
  sender_id BIGINT NOT NULL REFERENCES public.users(id) ON DELETE CASCADE,
  body TEXT NOT NULL CHECK (length(trim(body)) > 0),
  attachments JSONB NULL,
  is_internal BOOLEAN NOT NULL DEFAULT false,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

ALTER TABLE public.tickets ADD COLUMN IF NOT EXISTS assigned_to BIGINT NULL;
DO $$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fk_tk_assigned_to') THEN
    ALTER TABLE public.tickets ADD CONSTRAINT fk_tk_assigned_to
      FOREIGN KEY (assigned_to) REFERENCES public.users(id) ON DELETE SET NULL;
  END IF;
END $$;

CREATE INDEX IF NOT EXISTS idx_inventory_available ON public.inventory (variant_id, warehouse_id, quantity, reserved);
CREATE INDEX IF NOT EXISTS idx_stock_alerts_open ON public.stock_alerts (status, updated_at DESC);
CREATE INDEX IF NOT EXISTS idx_chat_threads_user_status ON public.chat_threads (user_id, status, updated_at DESC);
CREATE INDEX IF NOT EXISTS idx_chat_messages_thread_created ON public.chat_messages (thread_id, created_at);
CREATE INDEX IF NOT EXISTS idx_tickets_assigned_status ON public.tickets (assigned_to, status, updated_at DESC);
CREATE INDEX IF NOT EXISTS idx_orders_paid_at ON public.orders (paid_at) WHERE payment_status IN ('paid', 'partially_refunded');
CREATE INDEX IF NOT EXISTS idx_orders_user_created ON public.orders (user_id, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_products_published ON public.products (status, deleted_at) WHERE status = 'published' AND deleted_at IS NULL;

CREATE OR REPLACE FUNCTION public.set_updated_at()
RETURNS trigger LANGUAGE plpgsql SECURITY INVOKER SET search_path = public AS $$
BEGIN NEW.updated_at = now(); RETURN NEW; END;
$$;

DO $$
DECLARE t text;
BEGIN
  FOREACH t IN ARRAY ARRAY[
    'users','roles','permissions','user_addresses','brands','categories','attributes','attribute_values',
    'products','product_variants','warehouses','inventory','coupons','carts','orders','order_status_histories',
    'shipments','reviews','product_questions','shipping_zones','shipping_methods','banners','pages',
    'blog_posts','faqs','tickets','settings','stock_alerts','chat_threads'
  ] LOOP
    EXECUTE format('DROP TRIGGER IF EXISTS %I_updated_at ON public.%I', t, t);
    EXECUTE format('CREATE TRIGGER %I_updated_at BEFORE UPDATE ON public.%I FOR EACH ROW EXECUTE FUNCTION public.set_updated_at()', t, t);
  END LOOP;
END $$;

CREATE OR REPLACE FUNCTION public.refresh_inventory_snapshot()
RETURNS trigger LANGUAGE plpgsql SECURITY DEFINER SET search_path = public AS $$
DECLARE
  v_variant_id bigint := COALESCE(NEW.variant_id, OLD.variant_id);
  v_warehouse_id integer := COALESCE(NEW.warehouse_id, OLD.warehouse_id);
  v_available integer;
  v_threshold integer;
  v_alert_type text;
BEGIN
  UPDATE public.product_variants
  SET stock_total = COALESCE((SELECT SUM(GREATEST(i.quantity - i.reserved, 0))::integer
                              FROM public.inventory i WHERE i.variant_id = v_variant_id), 0)
  WHERE id = v_variant_id;

  SELECT GREATEST(quantity - reserved, 0), low_stock_threshold
    INTO v_available, v_threshold
  FROM public.inventory WHERE variant_id = v_variant_id AND warehouse_id = v_warehouse_id;
  IF NOT FOUND THEN RETURN COALESCE(NEW, OLD); END IF;

  v_alert_type := CASE WHEN v_available <= 0 THEN 'out_of_stock'
                       WHEN v_available <= v_threshold THEN 'low_stock'
                       ELSE NULL END;
  UPDATE public.stock_alerts
  SET status = 'resolved', resolved_at = now(), updated_at = now()
  WHERE variant_id = v_variant_id AND warehouse_id = v_warehouse_id AND status = 'open'
    AND (v_alert_type IS NULL OR alert_type <> v_alert_type);
  IF v_alert_type IS NOT NULL THEN
    INSERT INTO public.stock_alerts (variant_id, warehouse_id, available, threshold, alert_type, status, updated_at)
    VALUES (v_variant_id, v_warehouse_id, v_available, v_threshold, v_alert_type, 'open', now())
    ON CONFLICT (variant_id, warehouse_id, alert_type, status)
    DO UPDATE SET available = EXCLUDED.available, threshold = EXCLUDED.threshold, updated_at = now();
  END IF;
  RETURN COALESCE(NEW, OLD);
END;
$$;
DROP TRIGGER IF EXISTS inventory_snapshot_after_change ON public.inventory;
CREATE TRIGGER inventory_snapshot_after_change AFTER INSERT OR UPDATE OR DELETE ON public.inventory
FOR EACH ROW EXECUTE FUNCTION public.refresh_inventory_snapshot();

CREATE OR REPLACE FUNCTION public.current_app_user_id()
RETURNS bigint LANGUAGE sql STABLE SECURITY DEFINER SET search_path = public AS $$
  SELECT u.id FROM public.users u WHERE u.auth_user_id = auth.uid() AND u.deleted_at IS NULL LIMIT 1;
$$;

CREATE OR REPLACE FUNCTION public.has_permission(permission_name text)
RETURNS boolean LANGUAGE sql STABLE SECURITY DEFINER SET search_path = public AS $$
  SELECT EXISTS (
    SELECT 1
    FROM public.users u
    WHERE u.auth_user_id = auth.uid() AND u.status = 'active' AND u.deleted_at IS NULL
      AND (
        EXISTS (
          SELECT 1 FROM public.role_user ru
          JOIN public.permission_role pr ON pr.role_id = ru.role_id
          JOIN public.permissions p ON p.id = pr.permission_id
          WHERE ru.user_id = u.id AND p.name = permission_name
        )
        OR EXISTS (
          SELECT 1 FROM public.permission_user pu
          JOIN public.permissions p ON p.id = pu.permission_id
          WHERE pu.user_id = u.id AND pu.type = 'allow' AND p.name = permission_name
        )
      )
      AND NOT EXISTS (
        SELECT 1 FROM public.permission_user pu
        JOIN public.permissions p ON p.id = pu.permission_id
        WHERE pu.user_id = u.id AND pu.type = 'deny' AND p.name = permission_name
      )
  );
$$;
CREATE OR REPLACE FUNCTION public.is_staff()
RETURNS boolean LANGUAGE sql STABLE SECURITY DEFINER SET search_path = public AS $$
  SELECT public.has_permission('dashboard.view');
$$;

-- Row-level locking prevents two concurrent buyers from reserving the same stock.
CREATE OR REPLACE FUNCTION public.reserve_stock(p_order_id bigint, p_lines jsonb, p_warehouse_id integer DEFAULT NULL)
RETURNS void LANGUAGE plpgsql SECURITY DEFINER SET search_path = public AS $$
DECLARE
  line jsonb; v_warehouse_id integer := COALESCE(p_warehouse_id, (SELECT id FROM public.warehouses WHERE is_active ORDER BY id LIMIT 1));
  v_variant_id bigint; v_quantity integer; v_row public.inventory%ROWTYPE;
BEGIN
  IF v_warehouse_id IS NULL THEN RAISE EXCEPTION 'NO_ACTIVE_WAREHOUSE'; END IF;
  IF auth.role() <> 'service_role' AND NOT public.is_staff()
     AND NOT EXISTS (SELECT 1 FROM public.orders WHERE id = p_order_id AND user_id = public.current_app_user_id())
    THEN RAISE EXCEPTION 'FORBIDDEN' USING ERRCODE = '42501'; END IF;
  IF NOT EXISTS (SELECT 1 FROM public.orders WHERE id = p_order_id AND status = 'pending_payment')
    THEN RAISE EXCEPTION 'ORDER_NOT_RESERVABLE'; END IF;
  FOR line IN SELECT * FROM jsonb_array_elements(p_lines) LOOP
    v_variant_id := (line->>'variantId')::bigint; v_quantity := (line->>'quantity')::integer;
    IF v_quantity IS NULL OR v_quantity <= 0 THEN RAISE EXCEPTION 'INVALID_QUANTITY'; END IF;
    SELECT * INTO v_row FROM public.inventory WHERE variant_id = v_variant_id AND warehouse_id = v_warehouse_id FOR UPDATE;
    IF NOT FOUND OR GREATEST(v_row.quantity - v_row.reserved, 0) < v_quantity THEN RAISE EXCEPTION 'OUT_OF_STOCK'; END IF;
    UPDATE public.inventory SET reserved = reserved + v_quantity, updated_at = now()
      WHERE variant_id = v_variant_id AND warehouse_id = v_warehouse_id;
    INSERT INTO public.stock_movements (variant_id, warehouse_id, type, quantity, qty_before, qty_after, reference_type, reference_id)
      VALUES (v_variant_id, v_warehouse_id, 'reserve', v_quantity, v_row.quantity, v_row.quantity, 'order', p_order_id);
  END LOOP;
END;
$$;
CREATE OR REPLACE FUNCTION public.release_stock(p_order_id bigint, p_lines jsonb, p_warehouse_id integer DEFAULT NULL)
RETURNS void LANGUAGE plpgsql SECURITY DEFINER SET search_path = public AS $$
DECLARE line jsonb; v_warehouse_id integer := COALESCE(p_warehouse_id, (SELECT id FROM public.warehouses WHERE is_active ORDER BY id LIMIT 1));
  v_variant_id bigint; v_quantity integer;
BEGIN
  IF auth.role() <> 'service_role' AND NOT public.is_staff()
     AND NOT EXISTS (SELECT 1 FROM public.orders WHERE id = p_order_id AND user_id = public.current_app_user_id())
    THEN RAISE EXCEPTION 'FORBIDDEN' USING ERRCODE = '42501'; END IF;
  FOR line IN SELECT * FROM jsonb_array_elements(p_lines) LOOP
    v_variant_id := (line->>'variantId')::bigint; v_quantity := (line->>'quantity')::integer;
    UPDATE public.inventory SET reserved = GREATEST(reserved - v_quantity, 0), updated_at = now()
      WHERE variant_id = v_variant_id AND warehouse_id = v_warehouse_id;
    INSERT INTO public.stock_movements (variant_id, warehouse_id, type, quantity, qty_before, qty_after, reference_type, reference_id)
      SELECT v_variant_id, v_warehouse_id, 'release', v_quantity, quantity, quantity, 'order', p_order_id
      FROM public.inventory WHERE variant_id = v_variant_id AND warehouse_id = v_warehouse_id;
  END LOOP;
END;
$$;

-- Optional bridge for accounts created through Supabase Auth.
CREATE OR REPLACE FUNCTION public.handle_auth_user_created()
RETURNS trigger LANGUAGE plpgsql SECURITY DEFINER SET search_path = public AS $$
DECLARE new_user_id bigint;
BEGIN
  INSERT INTO public.users (auth_user_id, full_name, email, phone, password_hash, status, email_verified_at)
  VALUES (NEW.id,
    COALESCE(NULLIF(NEW.raw_user_meta_data->>'full_name', ''), split_part(COALESCE(NEW.email, 'کاربر کارزینتل'), '@', 1)),
    NULLIF(NEW.email, ''), COALESCE(NULLIF(NEW.phone, ''), 'a' || substr(replace(NEW.id::text, '-', ''), 1, 14)),
    NULL, 'active', NEW.email_confirmed_at)
  ON CONFLICT (auth_user_id) DO UPDATE SET email = EXCLUDED.email
  RETURNING id INTO new_user_id;
  INSERT INTO public.role_user (role_id, user_id) SELECT id, new_user_id FROM public.roles WHERE name = 'customer' ON CONFLICT DO NOTHING;
  RETURN NEW;
END;
$$;
DROP TRIGGER IF EXISTS on_auth_user_created ON auth.users;
CREATE TRIGGER on_auth_user_created AFTER INSERT ON auth.users FOR EACH ROW EXECUTE FUNCTION public.handle_auth_user_created();
CREATE OR REPLACE FUNCTION public.handle_auth_user_deleted()
RETURNS trigger LANGUAGE plpgsql SECURITY DEFINER SET search_path = public AS $$
BEGIN UPDATE public.users SET deleted_at = now(), status = 'suspended' WHERE auth_user_id = OLD.id; RETURN OLD; END;
$$;
DROP TRIGGER IF EXISTS on_auth_user_deleted ON auth.users;
CREATE TRIGGER on_auth_user_deleted AFTER DELETE ON auth.users FOR EACH ROW EXECUTE FUNCTION public.handle_auth_user_deleted();

CREATE OR REPLACE VIEW public.public_product_cards WITH (security_invoker = true) AS
SELECT p.id, p.slug, p.name, p.short_description, p.features, p.rating_avg, p.rating_count, p.min_price, p.max_price,
       COALESCE(SUM(GREATEST(v.stock_total, 0)), 0)::integer AS available_stock
FROM public.products p LEFT JOIN public.product_variants v ON v.product_id = p.id AND v.is_active AND v.deleted_at IS NULL
WHERE p.status = 'published' AND p.deleted_at IS NULL GROUP BY p.id;

-- ============================================================================
-- Safe seed: no admin password is stored in SQL. `npm run seed` creates it from env.
-- ============================================================================
INSERT INTO public.roles (name, label, description, is_system) VALUES
  ('super_admin', 'مدیر ارشد', 'دسترسی کامل به همه بخش‌ها', true),
  ('product_manager', 'مدیر محصول', 'محصول، دسته‌بندی، برند و موجودی', true),
  ('order_manager', 'مدیر سفارش', 'سفارش، پرداخت و بازپرداخت', true),
  ('support', 'پشتیبانی', 'پاسخ به مشتریان و تیکت‌ها', true),
  ('content_manager', 'مدیر محتوا', 'بنر، صفحه، وبلاگ و دیدگاه', true),
  ('warehouse', 'انباردار', 'موجودی و هشدارهای انبار', true),
  ('customer', 'مشتری', 'کاربر فروشگاه', true)
ON CONFLICT (name) DO UPDATE SET label = EXCLUDED.label, description = EXCLUDED.description, is_system = EXCLUDED.is_system;
SELECT setval(pg_get_serial_sequence('public.roles', 'id'), GREATEST((SELECT COALESCE(MAX(id), 1) FROM public.roles), 1), true);

INSERT INTO public.permissions (name, label, group_name) VALUES
  ('dashboard.view','مشاهده داشبورد','dashboard'),('users.view','مشاهده کاربران','users'),('users.create','ایجاد کاربر','users'),
  ('users.update','ویرایش کاربر','users'),('users.delete','حذف کاربر','users'),('users.assign_role','تخصیص نقش','users'),
  ('roles.view','مشاهده نقش‌ها','roles'),('roles.create','ایجاد نقش','roles'),('roles.update','ویرایش نقش','roles'),('roles.delete','حذف نقش','roles'),
  ('products.view','مشاهده محصولات','products'),('products.create','ایجاد محصول','products'),('products.update','ویرایش محصول','products'),
  ('products.delete','حذف محصول','products'),('products.publish','انتشار محصول','products'),('categories.manage','مدیریت دسته‌بندی‌ها','catalog'),
  ('brands.manage','مدیریت برندها','catalog'),('attributes.manage','مدیریت صفت‌ها','catalog'),('inventory.view','مشاهده موجودی','inventory'),
  ('inventory.manage','اصلاح موجودی','inventory'),('inventory.alerts','هشدار موجودی','inventory'),('orders.view','مشاهده سفارش‌ها','orders'),
  ('orders.update_status','تغییر وضعیت سفارش','orders'),('orders.cancel','لغو سفارش','orders'),('orders.refund','عودت وجه','orders'),
  ('payments.view','مشاهده تراکنش‌ها','payments'),('customers.view','مشاهده مشتریان','customers'),('customers.manage','مدیریت مشتریان','customers'),
  ('reviews.moderate','مدیریت دیدگاه‌ها','moderation'),('questions.moderate','پاسخ پرسش‌ها','moderation'),('coupons.manage','مدیریت کد تخفیف','marketing'),
  ('banners.manage','مدیریت بنرها','marketing'),('pages.manage','مدیریت صفحات','marketing'),('tickets.view','مشاهده پشتیبانی','tickets'),
  ('tickets.reply','پاسخ پشتیبانی','tickets'),('tickets.assign','تخصیص پشتیبانی','tickets'),('settings.manage','مدیریت تنظیمات','settings'),
  ('audit.view','مشاهده لاگ','settings'),('files.manage','مدیریت فایل‌ها','settings'),('reports.view','مشاهده گزارش‌ها','reports'),('reports.export','خروجی گزارش','reports')
ON CONFLICT (name) DO UPDATE SET label = EXCLUDED.label, group_name = EXCLUDED.group_name;
INSERT INTO public.permission_role (permission_id, role_id)
SELECT p.id, r.id FROM public.permissions p CROSS JOIN public.roles r WHERE r.name = 'super_admin' ON CONFLICT DO NOTHING;
INSERT INTO public.permission_role (permission_id, role_id)
SELECT p.id, r.id FROM public.permissions p CROSS JOIN public.roles r
WHERE r.name = 'product_manager' AND p.name IN ('dashboard.view','products.view','products.create','products.update','products.delete','products.publish','categories.manage','brands.manage','attributes.manage','inventory.view','inventory.manage','inventory.alerts','files.manage') ON CONFLICT DO NOTHING;
INSERT INTO public.permission_role (permission_id, role_id)
SELECT p.id, r.id FROM public.permissions p CROSS JOIN public.roles r
WHERE r.name = 'order_manager' AND p.name IN ('dashboard.view','orders.view','orders.update_status','orders.cancel','orders.refund','payments.view','customers.view','inventory.view','reports.view','reports.export') ON CONFLICT DO NOTHING;
INSERT INTO public.permission_role (permission_id, role_id)
SELECT p.id, r.id FROM public.permissions p CROSS JOIN public.roles r
WHERE r.name = 'support' AND p.name IN ('dashboard.view','orders.view','customers.view','tickets.view','tickets.reply','tickets.assign','inventory.alerts') ON CONFLICT DO NOTHING;
INSERT INTO public.permission_role (permission_id, role_id)
SELECT p.id, r.id FROM public.permissions p CROSS JOIN public.roles r
WHERE r.name = 'content_manager' AND p.name IN ('dashboard.view','banners.manage','pages.manage','reviews.moderate','questions.moderate','files.manage') ON CONFLICT DO NOTHING;
INSERT INTO public.permission_role (permission_id, role_id)
SELECT p.id, r.id FROM public.permissions p CROSS JOIN public.roles r
WHERE r.name = 'warehouse' AND p.name IN ('dashboard.view','products.view','orders.view','inventory.view','inventory.manage','inventory.alerts') ON CONFLICT DO NOTHING;
INSERT INTO public.warehouses (name, code, province, city) VALUES ('انبار مرکزی','MAIN','تهران','تهران') ON CONFLICT (code) DO NOTHING;
INSERT INTO public.settings ("key","value","group",type,is_public) VALUES
 ('store.name','کارزینتل','general','string',true),('store.name_en','Karzintell','general','string',true),
 ('store.currency','IRR','general','string',true),('store.tax_percent','9','billing','number',false),
 ('store.free_shipping_threshold','0','shipping','number',true),('store.shipping_flat','250000','shipping','number',false),
 ('store.support_phone','','general','string',true)
ON CONFLICT ("key") DO NOTHING;

INSERT INTO storage.buckets (id, name, public) VALUES ('product-media','product-media',true)
ON CONFLICT (id) DO UPDATE SET public = true;
DROP POLICY IF EXISTS product_media_public_read ON storage.objects;
CREATE POLICY product_media_public_read ON storage.objects FOR SELECT USING (bucket_id = 'product-media');
DROP POLICY IF EXISTS product_media_staff_insert ON storage.objects;
CREATE POLICY product_media_staff_insert ON storage.objects FOR INSERT TO authenticated WITH CHECK (bucket_id = 'product-media' AND public.has_permission('files.manage'));
DROP POLICY IF EXISTS product_media_staff_update ON storage.objects;
CREATE POLICY product_media_staff_update ON storage.objects FOR UPDATE TO authenticated USING (bucket_id = 'product-media' AND public.has_permission('files.manage')) WITH CHECK (bucket_id = 'product-media' AND public.has_permission('files.manage'));
DROP POLICY IF EXISTS product_media_staff_delete ON storage.objects;
CREATE POLICY product_media_staff_delete ON storage.objects FOR DELETE TO authenticated USING (bucket_id = 'product-media' AND public.has_permission('files.manage'));

-- RLS is deny-by-default after enable; the following are the minimum public/owner/operator grants.
DO $$
DECLARE t text;
BEGIN
  FOREACH t IN ARRAY ARRAY['users','roles','permissions','role_user','permission_role','permission_user','user_addresses','verification_codes','refresh_tokens','brands','categories','attributes','attribute_values','category_attribute','products','product_variants','product_variant_values','product_images','product_videos','tags','product_tags','product_relations','product_attributes','warehouses','inventory','stock_movements','stock_alerts','coupons','carts','cart_items','orders','order_items','order_status_histories','payments','shipments','coupon_usages','wallets','wallet_transactions','reviews','product_questions','wishlists','product_compares','shipping_zones','shipping_methods','banners','pages','blog_posts','faqs','tickets','ticket_messages','chat_threads','chat_messages','files','notifications','push_subscriptions','settings','audit_logs'] LOOP
    EXECUTE format('ALTER TABLE public.%I ENABLE ROW LEVEL SECURITY', t);
  END LOOP;
END $$;

-- Public catalog read policies.
DROP POLICY IF EXISTS categories_public_read ON public.categories; CREATE POLICY categories_public_read ON public.categories FOR SELECT USING (is_active AND deleted_at IS NULL);
DROP POLICY IF EXISTS brands_public_read ON public.brands; CREATE POLICY brands_public_read ON public.brands FOR SELECT USING (is_active AND deleted_at IS NULL);
DROP POLICY IF EXISTS attributes_public_read ON public.attributes; CREATE POLICY attributes_public_read ON public.attributes FOR SELECT USING (true);
DROP POLICY IF EXISTS attribute_values_public_read ON public.attribute_values; CREATE POLICY attribute_values_public_read ON public.attribute_values FOR SELECT USING (true);
DROP POLICY IF EXISTS category_attribute_public_read ON public.category_attribute; CREATE POLICY category_attribute_public_read ON public.category_attribute FOR SELECT USING (true);
DROP POLICY IF EXISTS products_public_read ON public.products; CREATE POLICY products_public_read ON public.products FOR SELECT USING (status = 'published' AND deleted_at IS NULL);
DROP POLICY IF EXISTS variants_public_read ON public.product_variants; CREATE POLICY variants_public_read ON public.product_variants FOR SELECT USING (is_active AND deleted_at IS NULL);
DROP POLICY IF EXISTS images_public_read ON public.product_images; CREATE POLICY images_public_read ON public.product_images FOR SELECT USING (true);
DROP POLICY IF EXISTS videos_public_read ON public.product_videos; CREATE POLICY videos_public_read ON public.product_videos FOR SELECT USING (true);
DROP POLICY IF EXISTS tags_public_read ON public.tags; CREATE POLICY tags_public_read ON public.tags FOR SELECT USING (true);
DROP POLICY IF EXISTS product_tags_public_read ON public.product_tags; CREATE POLICY product_tags_public_read ON public.product_tags FOR SELECT USING (true);
DROP POLICY IF EXISTS relations_public_read ON public.product_relations; CREATE POLICY relations_public_read ON public.product_relations FOR SELECT USING (true);
DROP POLICY IF EXISTS product_attributes_public_read ON public.product_attributes; CREATE POLICY product_attributes_public_read ON public.product_attributes FOR SELECT USING (true);
DROP POLICY IF EXISTS shipping_methods_public_read ON public.shipping_methods; CREATE POLICY shipping_methods_public_read ON public.shipping_methods FOR SELECT USING (is_active);
DROP POLICY IF EXISTS shipping_zones_public_read ON public.shipping_zones; CREATE POLICY shipping_zones_public_read ON public.shipping_zones FOR SELECT USING (is_active);
DROP POLICY IF EXISTS banners_public_read ON public.banners; CREATE POLICY banners_public_read ON public.banners FOR SELECT USING (is_active AND (starts_at IS NULL OR starts_at <= now()) AND (ends_at IS NULL OR ends_at >= now()));
DROP POLICY IF EXISTS pages_public_read ON public.pages; CREATE POLICY pages_public_read ON public.pages FOR SELECT USING (status = 'published');
DROP POLICY IF EXISTS blog_public_read ON public.blog_posts; CREATE POLICY blog_public_read ON public.blog_posts FOR SELECT USING (status = 'published');
DROP POLICY IF EXISTS faqs_public_read ON public.faqs; CREATE POLICY faqs_public_read ON public.faqs FOR SELECT USING (is_active);
DROP POLICY IF EXISTS reviews_public_read ON public.reviews; CREATE POLICY reviews_public_read ON public.reviews FOR SELECT USING (status = 'approved');
DROP POLICY IF EXISTS questions_public_read ON public.product_questions; CREATE POLICY questions_public_read ON public.product_questions FOR SELECT USING (status IN ('approved','answered'));

-- Customer-owned data.
DROP POLICY IF EXISTS users_self_read ON public.users; CREATE POLICY users_self_read ON public.users FOR SELECT TO authenticated USING (id = public.current_app_user_id() OR public.is_staff());
DROP POLICY IF EXISTS users_self_update ON public.users; CREATE POLICY users_self_update ON public.users FOR UPDATE TO authenticated USING (id = public.current_app_user_id() OR public.has_permission('users.update')) WITH CHECK (id = public.current_app_user_id() OR public.has_permission('users.update'));
DROP POLICY IF EXISTS addresses_owner_all ON public.user_addresses; CREATE POLICY addresses_owner_all ON public.user_addresses FOR ALL TO authenticated USING (user_id = public.current_app_user_id() OR public.has_permission('customers.manage')) WITH CHECK (user_id = public.current_app_user_id() OR public.has_permission('customers.manage'));
DROP POLICY IF EXISTS carts_owner_all ON public.carts; CREATE POLICY carts_owner_all ON public.carts FOR ALL TO authenticated USING (user_id = public.current_app_user_id()) WITH CHECK (user_id = public.current_app_user_id());
DROP POLICY IF EXISTS cart_items_owner_all ON public.cart_items; CREATE POLICY cart_items_owner_all ON public.cart_items FOR ALL TO authenticated USING (EXISTS (SELECT 1 FROM public.carts c WHERE c.id = cart_id AND c.user_id = public.current_app_user_id())) WITH CHECK (EXISTS (SELECT 1 FROM public.carts c WHERE c.id = cart_id AND c.user_id = public.current_app_user_id()));
DROP POLICY IF EXISTS orders_owner_read ON public.orders; CREATE POLICY orders_owner_read ON public.orders FOR SELECT TO authenticated USING (user_id = public.current_app_user_id() OR public.has_permission('orders.view'));
DROP POLICY IF EXISTS order_items_owner_read ON public.order_items; CREATE POLICY order_items_owner_read ON public.order_items FOR SELECT TO authenticated USING (EXISTS (SELECT 1 FROM public.orders o WHERE o.id = order_id AND (o.user_id = public.current_app_user_id() OR public.has_permission('orders.view'))));
DROP POLICY IF EXISTS notifications_owner_all ON public.notifications; CREATE POLICY notifications_owner_all ON public.notifications FOR ALL TO authenticated USING (user_id = public.current_app_user_id()) WITH CHECK (user_id = public.current_app_user_id());
DROP POLICY IF EXISTS push_owner_all ON public.push_subscriptions; CREATE POLICY push_owner_all ON public.push_subscriptions FOR ALL TO authenticated USING (user_id = public.current_app_user_id()) WITH CHECK (user_id = public.current_app_user_id());
DROP POLICY IF EXISTS wallets_owner_read ON public.wallets; CREATE POLICY wallets_owner_read ON public.wallets FOR SELECT TO authenticated USING (user_id = public.current_app_user_id() OR public.has_permission('customers.manage'));
DROP POLICY IF EXISTS wallet_transactions_owner_read ON public.wallet_transactions; CREATE POLICY wallet_transactions_owner_read ON public.wallet_transactions FOR SELECT TO authenticated USING (EXISTS (SELECT 1 FROM public.wallets w WHERE w.id = wallet_id AND (w.user_id = public.current_app_user_id() OR public.has_permission('customers.manage'))));
DROP POLICY IF EXISTS wishlist_owner_all ON public.wishlists; CREATE POLICY wishlist_owner_all ON public.wishlists FOR ALL TO authenticated USING (user_id = public.current_app_user_id()) WITH CHECK (user_id = public.current_app_user_id());
DROP POLICY IF EXISTS compare_owner_all ON public.product_compares; CREATE POLICY compare_owner_all ON public.product_compares FOR ALL TO authenticated USING (user_id = public.current_app_user_id()) WITH CHECK (user_id = public.current_app_user_id());
DROP POLICY IF EXISTS reviews_owner_insert ON public.reviews; CREATE POLICY reviews_owner_insert ON public.reviews FOR INSERT TO authenticated WITH CHECK (user_id = public.current_app_user_id());
DROP POLICY IF EXISTS questions_owner_insert ON public.product_questions; CREATE POLICY questions_owner_insert ON public.product_questions FOR INSERT TO authenticated WITH CHECK (user_id = public.current_app_user_id());

-- Support, chat, and operator permissions.
DROP POLICY IF EXISTS tickets_owner_read ON public.tickets; CREATE POLICY tickets_owner_read ON public.tickets FOR SELECT TO authenticated USING (user_id = public.current_app_user_id() OR public.has_permission('tickets.view'));
DROP POLICY IF EXISTS tickets_owner_insert ON public.tickets; CREATE POLICY tickets_owner_insert ON public.tickets FOR INSERT TO authenticated WITH CHECK (user_id = public.current_app_user_id());
DROP POLICY IF EXISTS tickets_staff_update ON public.tickets; CREATE POLICY tickets_staff_update ON public.tickets FOR UPDATE TO authenticated USING (public.has_permission('tickets.assign') OR public.has_permission('tickets.reply')) WITH CHECK (public.has_permission('tickets.assign') OR public.has_permission('tickets.reply'));
DROP POLICY IF EXISTS ticket_messages_visible ON public.ticket_messages; CREATE POLICY ticket_messages_visible ON public.ticket_messages FOR SELECT TO authenticated USING (EXISTS (SELECT 1 FROM public.tickets t WHERE t.id = ticket_id AND (t.user_id = public.current_app_user_id() OR public.has_permission('tickets.view'))) AND (NOT is_internal OR public.has_permission('tickets.view')));
DROP POLICY IF EXISTS ticket_messages_insert ON public.ticket_messages; CREATE POLICY ticket_messages_insert ON public.ticket_messages FOR INSERT TO authenticated WITH CHECK (sender_id = public.current_app_user_id() AND EXISTS (SELECT 1 FROM public.tickets t WHERE t.id = ticket_id AND (t.user_id = public.current_app_user_id() OR public.has_permission('tickets.reply'))));
DROP POLICY IF EXISTS chat_threads_visible ON public.chat_threads; CREATE POLICY chat_threads_visible ON public.chat_threads FOR SELECT TO authenticated USING (user_id = public.current_app_user_id() OR public.has_permission('tickets.view'));
DROP POLICY IF EXISTS chat_threads_insert ON public.chat_threads; CREATE POLICY chat_threads_insert ON public.chat_threads FOR INSERT TO authenticated WITH CHECK (user_id = public.current_app_user_id());
DROP POLICY IF EXISTS chat_threads_staff_update ON public.chat_threads; CREATE POLICY chat_threads_staff_update ON public.chat_threads FOR UPDATE TO authenticated USING (public.has_permission('tickets.assign') OR public.has_permission('tickets.reply')) WITH CHECK (public.has_permission('tickets.assign') OR public.has_permission('tickets.reply'));
DROP POLICY IF EXISTS chat_messages_visible ON public.chat_messages; CREATE POLICY chat_messages_visible ON public.chat_messages FOR SELECT TO authenticated USING (EXISTS (SELECT 1 FROM public.chat_threads t WHERE t.id = thread_id AND (t.user_id = public.current_app_user_id() OR public.has_permission('tickets.view'))) AND (NOT is_internal OR public.has_permission('tickets.view')));
DROP POLICY IF EXISTS chat_messages_insert ON public.chat_messages; CREATE POLICY chat_messages_insert ON public.chat_messages FOR INSERT TO authenticated WITH CHECK (sender_id = public.current_app_user_id() AND EXISTS (SELECT 1 FROM public.chat_threads t WHERE t.id = thread_id AND (t.user_id = public.current_app_user_id() OR public.has_permission('tickets.reply'))));

DROP POLICY IF EXISTS roles_staff_read ON public.roles; CREATE POLICY roles_staff_read ON public.roles FOR SELECT TO authenticated USING (public.is_staff());
DROP POLICY IF EXISTS permissions_staff_read ON public.permissions; CREATE POLICY permissions_staff_read ON public.permissions FOR SELECT TO authenticated USING (public.is_staff());
DROP POLICY IF EXISTS role_user_staff_read ON public.role_user; CREATE POLICY role_user_staff_read ON public.role_user FOR SELECT TO authenticated USING (public.is_staff());
DROP POLICY IF EXISTS permission_role_staff_read ON public.permission_role; CREATE POLICY permission_role_staff_read ON public.permission_role FOR SELECT TO authenticated USING (public.is_staff());
DROP POLICY IF EXISTS permission_user_staff_all ON public.permission_user; CREATE POLICY permission_user_staff_all ON public.permission_user FOR ALL TO authenticated USING (public.has_permission('roles.update')) WITH CHECK (public.has_permission('roles.update'));
DROP POLICY IF EXISTS products_staff_all ON public.products; CREATE POLICY products_staff_all ON public.products FOR ALL TO authenticated USING (public.has_permission('products.view')) WITH CHECK (public.has_permission('products.create') OR public.has_permission('products.update'));
DROP POLICY IF EXISTS variants_staff_all ON public.product_variants; CREATE POLICY variants_staff_all ON public.product_variants FOR ALL TO authenticated USING (public.has_permission('products.view')) WITH CHECK (public.has_permission('products.create') OR public.has_permission('products.update'));
DROP POLICY IF EXISTS images_staff_all ON public.product_images; CREATE POLICY images_staff_all ON public.product_images FOR ALL TO authenticated USING (public.has_permission('products.update') OR public.has_permission('files.manage')) WITH CHECK (public.has_permission('products.create') OR public.has_permission('products.update') OR public.has_permission('files.manage'));
DROP POLICY IF EXISTS inventory_staff_all ON public.inventory; CREATE POLICY inventory_staff_all ON public.inventory FOR ALL TO authenticated USING (public.has_permission('inventory.view')) WITH CHECK (public.has_permission('inventory.manage'));
DROP POLICY IF EXISTS movements_staff_read ON public.stock_movements; CREATE POLICY movements_staff_read ON public.stock_movements FOR SELECT TO authenticated USING (public.has_permission('inventory.view'));
DROP POLICY IF EXISTS alerts_staff_read ON public.stock_alerts; CREATE POLICY alerts_staff_read ON public.stock_alerts FOR SELECT TO authenticated USING (public.has_permission('inventory.alerts') OR public.has_permission('inventory.view'));
DROP POLICY IF EXISTS warehouses_staff_all ON public.warehouses; CREATE POLICY warehouses_staff_all ON public.warehouses FOR ALL TO authenticated USING (public.has_permission('inventory.view')) WITH CHECK (public.has_permission('inventory.manage'));
DROP POLICY IF EXISTS settings_public_read ON public.settings; CREATE POLICY settings_public_read ON public.settings FOR SELECT USING (is_public OR public.has_permission('settings.manage'));
DROP POLICY IF EXISTS settings_staff_all ON public.settings; CREATE POLICY settings_staff_all ON public.settings FOR ALL TO authenticated USING (public.has_permission('settings.manage')) WITH CHECK (public.has_permission('settings.manage'));
DROP POLICY IF EXISTS audit_staff_read ON public.audit_logs; CREATE POLICY audit_staff_read ON public.audit_logs FOR SELECT TO authenticated USING (public.has_permission('audit.view'));
DROP POLICY IF EXISTS files_owner_staff ON public.files; CREATE POLICY files_owner_staff ON public.files FOR SELECT TO authenticated USING (owner_id = public.current_app_user_id() OR public.has_permission('files.manage'));
DROP POLICY IF EXISTS files_staff_all ON public.files; CREATE POLICY files_staff_all ON public.files FOR ALL TO authenticated USING (public.has_permission('files.manage')) WITH CHECK (public.has_permission('files.manage'));
DROP POLICY IF EXISTS payments_owner_staff ON public.payments; CREATE POLICY payments_owner_staff ON public.payments FOR SELECT TO authenticated USING (public.has_permission('payments.view') OR EXISTS (SELECT 1 FROM public.orders o WHERE o.id = order_id AND o.user_id = public.current_app_user_id()));
DROP POLICY IF EXISTS shipments_owner_staff ON public.shipments; CREATE POLICY shipments_owner_staff ON public.shipments FOR SELECT TO authenticated USING (public.has_permission('orders.view') OR EXISTS (SELECT 1 FROM public.orders o WHERE o.id = order_id AND o.user_id = public.current_app_user_id()));

GRANT SELECT ON public.public_product_cards TO anon, authenticated;
GRANT EXECUTE ON FUNCTION public.current_app_user_id() TO authenticated;
GRANT EXECUTE ON FUNCTION public.has_permission(text) TO authenticated;
GRANT EXECUTE ON FUNCTION public.is_staff() TO authenticated;
GRANT EXECUTE ON FUNCTION public.reserve_stock(bigint, jsonb, integer) TO authenticated, service_role;
GRANT EXECUTE ON FUNCTION public.release_stock(bigint, jsonb, integer) TO authenticated, service_role;

-- End of migration.
